apiVersion: v1
kind: Service
metadata:
  name: argo01-service
  namespace: argo-01
  labels:
    app: argo01-service
spec:
  selector:
    app: argo01
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
